#!/usr/bin/env php
<?php
define('DS', DIRECTORY_SEPARATOR);
define('ROOT_PATH', __DIR__ . DS);
define('APP_PATH', ROOT_PATH. 'app' . DS );
define('CONF_PATH', ROOT_PATH . 'config' . DS);
define('RUN_PATH', ROOT_PATH . 'runtime' . DS);
define('LOG_PATH', RUN_PATH . 'logs' . DS);
define('TEMP_PATH', RUN_PATH . 'temp' . DS);
define('CONTROLLER_NAMESPACE', '\\App\\Controller\\');

require ROOT_PATH . 'vendor/julibo/msfoole-core/src/console.php';
