# msfoole
MSFOOLE__HOST: 0.0.0.0
MSFOOLE__PORT: 9000
MSFOOLE__MONITOR__PATH: app/,vendor/julibo/msfoole/src/
MSFOOLE__MONITOR__INTERVAL: 10
MSFOOLE__WEBSOCKET__KEY: 700040D41F47592C
MSFOOLE__WEBSOCKET__VI: 4937682F63AA8FC2
MSFOOLE__WEBSOCKET__SIGN: false
MSFOOLE__TABLE__SIZE: 1024
MSFOOLE__CHANNEL__SIZE: 65536
MSFOOLE__CHANNEL__POOL: 1
MSFOOLE__OPTION__WORKER_NUM: 1
MSFOOLE__OPTION__MAX_REQUEST: 10000
MSFOOLE__OPTION__LOG_LEVEL: 0
MSFOOLE__OPTION__DAEMONIZE: false
MSFOOLE__OPTION__HEARTBEAT_CHECK_INTERVAL: 1
MSFOOLE__OPTION__HEARTBEAT_IDLE_TIME: 120