# application
APPLICATION__DEBUG: true
APPLICATION__ACCESS__ORIGIN: http://127.0.0.1:8080
APPLICATION__TOKEN__SWITCH: true
APPLICATION__TOKEN__CODE: true
# cache
CACHE__DEFAULT__HOST: 127.0.0.1
CACHE__DEFAULT__PORT: 6379
CACHE__DEFAULT__PASSWORD:
CACHE__DEFAULT__DB: 0
# extra
EXTRA__SMS__KEY: b583e0692cd9dbc586ef
EXTRA__SMS__USER: zgsof
EXTRA__DD__HOOK: 84fe66b00d96a4492df3da0c3f8f49735c2b505c17c68f4f97cf77a73fda8336
# log
LOG__LEVEL: slow,sql,debug,info,notice,warning,error,critical,alert,emergency
LOG__DEBUG: true
LOG__RECORD_TRACE: true
# msfoole
MSFOOLE__HOST: 0.0.0.0
MSFOOLE__PORT: 9111
MSFOOLE__MONITOR__PATH: app/,vendor/julibo/msfoole-core/src/
MSFOOLE__MONITOR__INTERVAL: 10
MSFOOLE__WEBSOCKET__KEY: 700040D41F47592C
MSFOOLE__WEBSOCKET__VI: 4937682F63AA8FC2
MSFOOLE__WEBSOCKET__SIGN: false
MSFOOLE__TABLE__SIZE: 1024
MSFOOLE__CHANNEL__CAPACITY: 100
MSFOOLE__OPTION__WORKER_NUM: 1
MSFOOLE__OPTION__MAX_REQUEST: 10000
MSFOOLE__OPTION__LOG_LEVEL: 0
MSFOOLE__OPTION__DAEMONIZE: false
MSFOOLE__OPTION__HEARTBEAT_CHECK_INTERVAL: 1
MSFOOLE__OPTION__HEARTBEAT_IDLE_TIME: 120